[theme]
primaryColor="#F63366"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
textColor="#262730"
font="sans serif"

[server]
# Enable serving files from a `static` directory in the running app's
# directory.
# Default: false
enableStaticServing = true